"use client"; // Directiva para Next.js 13+

import "./globals.css";
import { AppWrapper } from "./context/index.jsx";
import Navbar from "./components/navbar";
import { SessionProvider } from "next-auth/react";

// Metadata para la página
// export const metadata = {
//   title: "Lyric Checker",
//   description: "Generated by create next app",
// };

// Definición del componente RootLayout
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionProvider>
        <AppWrapper>
          <body>
            <Navbar />
            {children}
          </body>
        </AppWrapper>
      </SessionProvider>
    </html>
  );
}
